# Generated by Django 5.2.7 on 2026-09-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_attendancesession_rotation_interval_and_more'),
        ('attendance', '0013_studentprofile_semester'),
    ]

    operations = [
    ]
